/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.telegram.telegrambots.*;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
